apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: portfolio-runner
  namespace: arc-system
spec:
  replicas: 1
  template:
    spec:
      repository: MiguelABFlores/miguelabf-devops-portfolio
      # Imagen con docker buildx preinstalado
      image: summerwind/actions-runner-dind:latest
      # Necesita acceso a Docker para buildx
      dockerEnabled: true
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
      # Para poder hacer push a Harbor (HTTP)
      env:
        - name: DOCKER_OPTS
          value: "--insecure-registry harbor.192.168.0.240.nip.io"
